apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maor-klir/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      valuesObject:
        fullnameOverride: guestbook-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: default

# NEW tracking-id: guestbook:/Service:default/guestbook-helm-guestbook
# OLD tracking-id: guestbook:/Service:default/guestbook-ui